language: node_js

os:
  - osx

node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
  
script: 
  #./node_modules/mocha/bin/mocha tests/*.test.js
before_install:
  - npm install
#  - brew install android-platform-tools;
  - gem install cocoapods